development:
  adapter: mysql2
  database: estore_development
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: estore_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: estore_production
  username: root
  pool: 5
  timeout: 5000